export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_PROFILE = "LOAD_PROFILE"


export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"

export const SELECTED_VIDEOS_REQUEST = "SELECTED_VIDEOS_REQUEST"
export const SELECTED_VIDEOS_SUCCESS = "SELECTED_VIDEOS_SUCCESS"
export const SELECTED_VIDEOS_FAIL = "SELECTED_VIDEOS_FAIL"

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"